sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - bower_components
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'npm run-script test'
  - 'npm run-script build'
  - 'sh sync-ghpages.sh'
env:
  global:
  - GH_REF: github.com/TherapiePapst/homepage.git
