sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - bower_components
node_js:
  - '6.10.3'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'npm run-script test'
  - 'npm run-script build'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: dist
  on:
    branch: master
